# 日志相关参数配置
logger:
  auto-init: true
  # 日志开启级别
  level: debug
  # 日志文件的输出目录
  directory: "./logs"
  # 日志开启哪些端
  enable:
    # 是否开启标准输出
    stdout: true
    # 是否开启文件输出
    file: true

# 爬虫相关配置
crawler:
  # 爬虫使用到的代理
  proxy:
    # 动态代理
    dynamic-proxy: "xxx"
  # 爬虫的队列
  queue:
    # 队列名称
    name: "xxxx"
  # 消费者参数 
  consumer:
    # 消费者数量
    worker-num: 1

# OSS相关参数配置
oss:
  # 公网
  endpoint: "oss-cn-beijing.aliyuncs.com"
  # 认证相关
  access-key-id: "xxxx"
  access-key-secret: "xxxx"

# Redis配置
redis:
  auto-init: true
  address: "xxx:6379"
  passwd: "xxxx:xxxx"

# 数据库配置
database:
  mysql:
    auto-init: true
    dsn: "xxxx:xxxxxxxx@tcp(xxxx)/xxxx?parseTime=true&loc=Local&charset=utf8mb4"
    # 使用到的驱动都有哪些
    driver:
      sqlx: true
      gorm: true
    connection:
      max-idle: 10
      max-open: 100
      max-lifetime: 1000_000

